// Code generated by entc, DO NOT EDIT.

package codegen

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/alexgtn/go-linkshort/tools/ent/codegen/nordpooldayahead"
	"github.com/alexgtn/go-linkshort/tools/ent/codegen/predicate"
)

// NordPoolDayAheadDelete is the builder for deleting a NordPoolDayAhead entity.
type NordPoolDayAheadDelete struct {
	config
	hooks    []Hook
	mutation *NordPoolDayAheadMutation
}

// Where appends a list predicates to the NordPoolDayAheadDelete builder.
func (npdad *NordPoolDayAheadDelete) Where(ps ...predicate.NordPoolDayAhead) *NordPoolDayAheadDelete {
	npdad.mutation.Where(ps...)
	return npdad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (npdad *NordPoolDayAheadDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(npdad.hooks) == 0 {
		affected, err = npdad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NordPoolDayAheadMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			npdad.mutation = mutation
			affected, err = npdad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(npdad.hooks) - 1; i >= 0; i-- {
			if npdad.hooks[i] == nil {
				return 0, fmt.Errorf("codegen: uninitialized hook (forgotten import codegen/runtime?)")
			}
			mut = npdad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, npdad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (npdad *NordPoolDayAheadDelete) ExecX(ctx context.Context) int {
	n, err := npdad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (npdad *NordPoolDayAheadDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: nordpooldayahead.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: nordpooldayahead.FieldID,
			},
		},
	}
	if ps := npdad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, npdad.driver, _spec)
}

// NordPoolDayAheadDeleteOne is the builder for deleting a single NordPoolDayAhead entity.
type NordPoolDayAheadDeleteOne struct {
	npdad *NordPoolDayAheadDelete
}

// Exec executes the deletion query.
func (npdado *NordPoolDayAheadDeleteOne) Exec(ctx context.Context) error {
	n, err := npdado.npdad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{nordpooldayahead.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (npdado *NordPoolDayAheadDeleteOne) ExecX(ctx context.Context) {
	npdado.npdad.ExecX(ctx)
}
