// Code generated by entc, DO NOT EDIT.

package codegen

import (
	"time"

	"github.com/alexgtn/go-linkshort/tools/ent/codegen/nordpooldayahead"
	"github.com/alexgtn/go-linkshort/tools/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	nordpooldayaheadFields := schema.NordPoolDayAhead{}.Fields()
	_ = nordpooldayaheadFields
	// nordpooldayaheadDescDate is the schema descriptor for date field.
	nordpooldayaheadDescDate := nordpooldayaheadFields[0].Descriptor()
	// nordpooldayahead.DateValidator is a validator for the "date" field. It is called by the builders before save.
	nordpooldayahead.DateValidator = nordpooldayaheadDescDate.Validators[0].(func(string) error)
	// nordpooldayaheadDescValue is the schema descriptor for value field.
	nordpooldayaheadDescValue := nordpooldayaheadFields[1].Descriptor()
	// nordpooldayahead.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	nordpooldayahead.ValueValidator = nordpooldayaheadDescValue.Validators[0].(func(float64) error)
	// nordpooldayaheadDescRegion is the schema descriptor for region field.
	nordpooldayaheadDescRegion := nordpooldayaheadFields[2].Descriptor()
	// nordpooldayahead.RegionValidator is a validator for the "region" field. It is called by the builders before save.
	nordpooldayahead.RegionValidator = nordpooldayaheadDescRegion.Validators[0].(func(string) error)
	// nordpooldayaheadDescCreatedAt is the schema descriptor for created_at field.
	nordpooldayaheadDescCreatedAt := nordpooldayaheadFields[3].Descriptor()
	// nordpooldayahead.DefaultCreatedAt holds the default value on creation for the created_at field.
	nordpooldayahead.DefaultCreatedAt = nordpooldayaheadDescCreatedAt.Default.(func() time.Time)
}
