// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// NordPoolDayAhead is the predicate function for nordpooldayahead builders.
type NordPoolDayAhead func(*sql.Selector)
